"use client";
import * as React from "react";
import {QueryPanel,matches,type Query} from "./query-panel";
import {toast} from "sonner";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";

type Row={id:string;waybill:string;bol:string;fc:string;desired:string;actual:string;source:string;next:string;status:string;receiptStatus:string;allow:boolean;eligibility?:string;shouldProvide?:boolean;settingIssue?:boolean;stopped?:boolean;missing?:string;version?:number};
const warehouseZones:Record<string,string>={ONT8:"America/Los_Angeles",LAX9:"America/Los_Angeles",SMF3:"America/Los_Angeles",LGB8:"America/Los_Angeles",GYR2:"America/Phoenix",SBD1:"America/Los_Angeles",FTW1:"America/Chicago",ABQ2:"America/Denver"};
export function localDate(fc:string,now=new Date()){const tz=warehouseZones[fc];if(!tz)return "";return new Intl.DateTimeFormat("en-CA",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit"}).format(now);}
export function localStamp(){return new Intl.DateTimeFormat("zh-CN",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date())+" 北京";}
export function windowDates(value:string){const d=value.match(/\d{4}-\d{2}-\d{2}|\d{2}-\d{2}/g)||[];return {start:d[0]||"",end:d[1]?.length===5?d[0]?.slice(0,5)+d[1]:d[1]||""};}
export function blockNext(r:Row){return "每日当地10:00、19:00 / 截止"+windowDates(r.desired).end+"（含当日）";}
export function canRetryDw(r:Row){const today=localDate(r.fc),target=windowDates(r.desired),actual=windowDates(r.actual);return !!today&&target.end>=today&&(!actual.end||actual.end>=today)&&!r.settingIssue&&!r.stopped&&!r.missing&&r.allow&&r.receiptStatus!=="已完成"&&r.status==="BLOCKED";}
export function exportErrors(tasks:Array<{id:string;fba:string;api:string;trigger:string;error:string;status:string}>,rows:Row[],items?:Array<{id:string;waybill:string;status:string;error:string;target:string}>) {
 const header=["FBA货件号","运单号","提单号","当前Amazon仓点","任务编号","业务批次号","接口名称","触发来源","我方期望DW","Amazon当前DW","期望DW来源","业务阶段","修改资格","货件设置","Amazon错误码","Amazon错误信息","系统异常分类","任务创建时间","最近执行时间","操作人"];
 const values=tasks.filter(t=>["需人工","等待重试"].includes(t.status)).map(t=>{const r=rows.find(r=>r.id===t.fba);return[t.fba,r?.waybill||"",r?.bol||"",r?.fc||"",t.id,"",t.api,t.trigger,r?.desired||"",r?.actual||"",r?.source||"",r?.receiptStatus||"",r?.allow?"允许修改":"卖家管理",r?.settingIssue?"货件设置异常":"--",t.error.split(" · ")[0],t.error,r?.settingIssue?"货件设置异常":t.error.includes("BLOCK")?"目标不可用":"接口异常","—","—","系统"]});
 const customer=(items||[]).filter(i=>i.status==="等待客户修改");const customerIds=new Set(customer.map(i=>i.id));rows.filter(r=>r.receiptStatus!=="已完成"&&(r.settingIssue||!r.allow)&&!customerIds.has(r.id)&&items===undefined).forEach(r=>customer.push({id:r.id,waybill:r.waybill,status:"等待客户修改",error:r.settingIssue?"货件设置异常":"卖家管理",target:r.desired}));customer.forEach(i=>{const r=rows.find(r=>r.id===i.id);values.push([i.id,i.waybill,r?.bol||"",r?.fc||"","","","","人工计划",i.target,r?.actual||"","人工登记",r?.receiptStatus||"",r?.allow?"允许修改":"卖家管理",r?.settingIssue?"货件设置异常":"--","",i.error,"等待客户修改","—","—","—"])});
 const quote=(x:string)=>'"'+x.replaceAll('"','""')+'"';const blob=new Blob(["\ufeff"+[header,...values].map(r=>r.map(quote).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="Amazon异常明细.csv";a.click();URL.revokeObjectURL(url);toast.success("已下载FBA级异常明细");
}
export function RetryQueue({rows,onRetry}:{rows:Row[];onRetry:(ids:string[])=>void}){
 const [selected,setSelected]=React.useState<string[]>([]);const [queued,setQueued]=React.useState<string[]>([]);
 const [q,setQ]=React.useState<Query>({});
 const records=rows.filter(r=>matches(r.id,q.fba||"")&&matches(r.waybill,q.waybill||"")&&(!q.reason||q.reason==="all"||(q.reason==="人工BLOCK"?r.status==="BLOCKED":q.reason==="货件设置异常"?r.settingIssue:q.reason==="窗口过期"?r.stopped:q.reason==="运输信息缺失"?r.missing:r.status==="待同步"))).filter(r=>r.status==="BLOCKED"||r.settingIssue||r.stopped||r.missing||r.status==="待同步");
 return <section className="panel"><div className="panel-head"><strong>重试与等待任务</strong><Button disabled={!selected.length} onClick={()=>{const valid=selected.filter(id=>rows.some(r=>r.id===id&&canRetryDw(r)));onRetry(valid);setQueued([...queued,...valid]);setSelected([])}}>批量重试 {selected.length||""}</Button></div><QueryPanel compact fields={[["fba","FBA货件号"],["waybill","运单号"]]} selects={[{key:"reason",label:"等待或停止原因",options:["人工BLOCK","货件设置异常","窗口过期","运输信息缺失","待同步"]}]} onApply={v=>{setQ(v);setSelected([])}}/><p style={{padding:"0 16px",fontSize:14}}>展示当前全部未结束的重试、等待事项及停止原因，不限当天；历史执行结果在业务批次和接口记录查看。</p><div className="table-wrap"><Table><TableHeader><TableRow>{["选择","FBA货件","任务类型","目标DW","等待或终止原因","下一次执行 / 截止","操作"].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{records.map(r=><TableRow key={r.id}><TableCell><input type="checkbox" disabled={!canRetryDw(r)} checked={selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(x=>x!==r.id))}/></TableCell><TableCell>{r.id}<small className="sub">{r.waybill}</small></TableCell><TableCell>{r.missing?"运输信息补偿":r.status==="BLOCKED"?"人工窗口BLOCK监控":"DW同步"}</TableCell><TableCell>{r.desired}</TableCell><TableCell>{r.stopped?"自动处理已结束":r.settingIssue?"已结束：货件设置异常，不可恢复":r.missing?"本地等待："+r.missing:queued.includes(r.id)?"待执行":r.status==="BLOCKED"?"目标BLOCK · 自动重试中":"待调度"}</TableCell><TableCell>{r.stopped||r.settingIssue?"不再自动执行":r.status==="BLOCKED"?blockNext(r):r.missing?"每天本地检查；数据补齐立即触发":"按平台限流排队"}</TableCell><TableCell><Button variant="outline" disabled={!canRetryDw(r)||queued.includes(r.id)} onClick={()=>{if(!canRetryDw(r))return;onRetry([r.id]);setQueued([...queued,r.id])}}>重试</Button></TableCell></TableRow>)}</TableBody></Table></div><p style={{padding:16}}>自动预估被BLOCK时选择晚于原目标的可选一周（只选一周），不进入人工窗口每日监控。</p></section>;
}
type Case={id:string;fba:string;waybill:string;reason:string;target:string;version:number;status:string;history:string[];feedback?:string};
let cases:Case[]=[
 {id:"N-0001",fba:"FBA1D4B7X9NQ",waybill:"FD2609150036",reason:"货件设置异常",target:"2026-10-11 ～ 10-17",version:1,status:"待通知",history:["10-05 08:55 首次发现WORKING，暂停全部DW自动任务"]},
 {id:"N-0002",fba:"FBA1H5R2V8JD",waybill:"FD2609100077",reason:"卖家未授权",target:"2026-11-01 ～ 11-07",version:1,status:"待客户处理",history:["10-05 09:00 人工发送：请开启授权；我方计划11-01～11-07"]},
 {id:"N-0003",fba:"FBA1EXP00001",waybill:"FD2609180041",reason:"Amazon当前DW过期",target:"2026-10-11 ～ 10-17",version:1,status:"待通知",history:["10-05 06:30 当前DW已过期，货件未完成，结束自动处理"]},
 {id:"N-0004",fba:"FBA1M8K2Q7TX",waybill:"FD2609180002",reason:"人工窗口持续BLOCK",target:"2026-10-04 ～ 10-10",version:1,status:"待通知",history:["演示：运营判断需客户协助；自动通知阈值待确定"]}
];
const listeners=new Set<()=>void>();const emit=()=>listeners.forEach(f=>f());
let bound=false;
export function bind(){if(bound)return;bound=true;window.addEventListener("dw-followup",e=>{const {row,reason}=(e as CustomEvent<{row:Row;reason:string}>).detail;const existing=cases.find(c=>c.fba===row.id&&!["已完成","已关闭"].includes(c.status));if(existing){existing.target=row.desired;existing.version=row.version||1;existing.reason=reason;existing.status="待通知";existing.history.push("人工更新计划："+row.desired+"，更新通知内容；既有发送记录保留");}else cases.unshift({id:"N-"+Date.now(),fba:row.id,waybill:row.waybill,reason,target:row.desired,version:row.version||1,status:"待通知",history:["新的有效计划需通知客户"]});emit();});}
function content(c:Case){const action=c.reason==="卖家未授权"?"请允许FIST承运商更新送达时段；无法授权时请自行更新并反馈。":c.reason==="货件设置异常"?"该货件存在设置异常，根据当前客户真实反馈，卖家或承运商无法恢复。系统已结束DW自动处理，请线下跟进实际送仓及后续安排。":c.reason.includes("过期")?"Amazon当前送达窗口已过期，货件尚未完成。系统已结束自动更新，请反馈实际送仓及后续安排。":"目标送达窗口持续不可用，请协商后续送仓计划；卖家自行修改也可能受BLOCK限制。";return "货件："+c.fba+"（"+c.waybill+"）\n"+action+"\n我方当前计划送达窗口："+c.target+"。请按此有效计划安排处理。";}
export function CustomerFollowup({only}:{only?:string}){
 const [,force]=React.useReducer(x=>x+1,0);const [query,setQuery]=React.useState("");const [status,setStatus]=React.useState("全部");const [active,setActive]=React.useState<string|null>(null);const [feedback,setFeedback]=React.useState("");const [sender,setSender]=React.useState("Admin");const [channel,setChannel]=React.useState("微信人工发送");
 React.useEffect(()=>{bind();listeners.add(force);return()=>{listeners.delete(force)}},[]);
 const c=cases.find(x=>x.id===active);const change=(next:string,note:string)=>{if(!c)return;c.status=next;c.history.push("10-05 17:45 · "+note);emit();};
 const visible=cases.filter(c=>(!only||c.fba===only)&&(status==="全部"||c.status===status)&&(c.fba+c.waybill+c.reason).includes(query));
 return <section className="panel"><div className="panel-head"><strong>客户通知与跟进</strong><span>二期规划 · 人工通知及跟进</span></div><div style={{display:"flex",gap:12,padding:16}}><Input placeholder="FBA / 运单 / 问题" value={query} onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}>{["全部","待通知","待客户处理","待核实","已完成","已关闭"].map(x=><option key={x}>{x}</option>)}</select></div><div className="table-wrap"><Table><TableHeader><TableRow>{["FBA货件 / 运单","需客户处理的问题","当前有效计划","跟进状态","操作"].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.map(x=><TableRow key={x.id}><TableCell>{x.fba}<small className="sub">{x.waybill}</small></TableCell><TableCell>{x.reason}</TableCell><TableCell>{x.target}</TableCell><TableCell>{x.status}</TableCell><TableCell><Button variant="outline" onClick={()=>{setActive(x.id);setFeedback(x.feedback||"")}}>查看 / 跟进</Button></TableCell></TableRow>)}</TableBody></Table></div>{!visible.length&&<p style={{padding:20}}>暂无需要客户处理的通知待办。内部预估目标过期不单独通知。</p>}<Dialog open={!!c} onOpenChange={v=>!v&&setActive(null)}><DialogContent style={{maxWidth:760,maxHeight:"85vh",overflowY:"auto"}}><DialogHeader><DialogTitle>{c?.fba} · 客户跟进</DialogTitle><DialogDescription>{c?.reason} · {c?.status}</DialogDescription></DialogHeader>{c&&<><Textarea value={content(c)} readOnly rows={6}/><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(content(c));toast.success("内容已复制；请发送后登记") }catch{toast.info("请手动复制上方内容")}}}>复制通知内容</Button><div style={{display:"flex",gap:12}}><Input aria-label="发送人" value={sender} onChange={e=>setSender(e.target.value)}/><Input aria-label="发送渠道" value={channel} onChange={e=>setChannel(e.target.value)}/></div><Button disabled={c.status!=="待通知"||!sender||!channel} onClick={()=>change("待客户处理",sender+" · "+channel+" · 已人工发送\n"+content(c))}>登记已发送</Button><Textarea placeholder="登记客户反馈 / 后续安排" value={feedback} onChange={e=>setFeedback(e.target.value)}/><Button variant="outline" disabled={!feedback.trim()} onClick={()=>{c.feedback=feedback;change("待核实","客户反馈："+feedback)}}>登记反馈 / 后续安排</Button><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Button disabled={c.status!=="待核实"||!feedback.trim()} onClick={()=>change("已完成",(c.reason==="货件设置异常"||c.reason.includes("过期")?"运营登记后续安排并结束跟进：":"运营核实已解决，证据：")+feedback+"；跟进结束不恢复DW自动处理")}>{c.reason==="货件设置异常"||c.reason.includes("过期")?"结束跟进":"核实已解决"}</Button><Button variant="outline" onClick={()=>change("已关闭","运营关闭跟进；保留全部历史")}>关闭跟进</Button></div><strong>跟进与发送历史</strong>{c.history.map((h,i)=><p key={i} style={{whiteSpace:"pre-wrap",borderBottom:"1px solid #e2e8f0",paddingBottom:12}}>{h}</p>)}<small>人工核实客户处理结果不恢复DW处理；设置异常及Amazon窗口过期均不可恢复。</small></>}</DialogContent></Dialog></section>;
}

type DemoTask={id:string;fba:string;api:string;trigger:string;status:string;error:string;batchId?:string;tries?:number};
// 仅保留本次浏览器会话观察到的失败样例，不冒充生产调用历史。
const demoFailures=new Map<string,{task:DemoTask;row?:Row}>();
export function rememberDemoFailures(tasks:DemoTask[],rows:Row[]){
 tasks.filter(t=>["需人工","等待重试","失败"].includes(t.status)).forEach(t=>{
  const key=t.id+":"+(t.tries||0);
  if(!demoFailures.has(key)){const row=rows.find(r=>r.id===t.fba);demoFailures.set(key,{task:{...t},row:row?{...row}:undefined})}
 });
}
export function exportAllErrors(tasks:DemoTask[],rows:Row[],batches:Array<{id:string;created:string;kind?:string;items?:Array<{id:string;waybill:string;status:string;error:string;target:string}>}>){
 rememberDemoFailures(tasks,rows);
 const header=["FBA货件号","运单号","提单号","仓点","任务编号","业务批次号","任务类型","触发来源","异常环节","异常分类","接口名称","错误码","业务返回值","错误原因","执行时我方目标DW","执行时Amazon DW","目标来源","业务阶段","修改资格","货件设置","任务创建时间","失败或发现时间","最近执行时间","操作人","数据来源"];
 const records:string[][]=[];
 const add=(r:Row|undefined,id:string,task:string,batch:string,kind:string,trigger:string,phase:string,category:string,api:string,code:string,value:string,reason:string,target:string,time:string,origin:string)=>records.push([id,r?.waybill||"",r?.bol||"",r?.fc||"",task,batch,kind,trigger,phase,category,api,code,value,reason,target,r?.actual||"",r?.source||"",r?.receiptStatus||"",r?.eligibility||"未记录",r?.settingIssue?"货件设置异常":"--","未记录",time,"未记录","未记录",origin]);
 demoFailures.forEach(({task:t,row:r})=>{
  const blocked=t.error.includes("BLOCK"),calculation=t.api==="DW 规则计算";
  add(r,t.fba,t.id,t.batchId||"",t.api,t.trigger,blocked?"窗口选项匹配":calculation?"内部计算":"接口执行",blocked||calculation?"业务执行异常":"接口失败样例",calculation?"":t.api,t.error.match(/\b[A-Z][A-Z0-9_]{3,}\b/)?.[0]||"","",t.error,r?.desired||"","未记录","演示会话观察快照，非生产历史");
 });
 // 批次目标取登记时保存值；缺少当时其他字段时留空，不用当前货件反推历史。
 batches.forEach(b=>(b.items||[]).filter(i=>["失败","等待前置","人工BLOCK监控"].includes(i.status)).forEach(i=>add(undefined,i.id,"",b.id,b.kind||"人工DW登记","业务批次","业务处理","业务执行异常","","","",i.error==="—"?"目标不可用或前置未满足":i.error,i.target,b.created,"演示批次保存快照")));
 rows.filter(r=>r.settingIssue||r.stopped||r.eligibility==="卖家管理"||r.missing).forEach(r=>add(r,r.id,"","","当前异常事实","当前快照","业务资格或停止","当前业务异常","",r.settingIssue?"INVALID_FBA_SHIPMENT_STATUS":"",r.eligibility==="卖家管理"?"修改资格=FALSE":"",r.settingIssue?"货件设置异常，DW自动处理已结束":r.stopped?"Amazon窗口过期，DW自动处理已结束":r.missing?"缺少："+r.missing:"卖家管理，未提交DW",r.desired,"当前快照","当前异常快照"));
 const quote=(v:string)=>'"'+v.replaceAll('"','""')+'"';const blob=new Blob(["\ufeff"+[header,...records].map(r=>r.map(quote).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="Amazon全部失败及异常原因.csv";a.click();URL.revokeObjectURL(url);toast.success("已导出演示失败样例及当前异常；非生产历史");
}
