"use client";
import * as React from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from "@/components/ui/table";
import {exportErrors,canRetryDw} from "./lifecycle";
import {toast} from "sonner";
type Task={id:string;fba:string;api:string;trigger:string;status:"成功"|"等待重试"|"需人工"|"执行中"|"已跳过";tries:number;error:string;next:string};
type Row={id:string;waybill:string;bol:string;fc:string;desired:string;actual:string;source:string;next:string;status:string;receiptStatus:string;allow:boolean;settingIssue?:boolean;stopped?:boolean;missing?:string;version?:number};
type Batch={id:string;source:string;created:string;operator:string;total:number;success:number;retrying:number;failed:number;ineligible:number;target:string;status:string};
export function PhaseOneTasks({tasks,setTasks,rows,batches,onView}:{tasks:Task[];setTasks:React.Dispatch<React.SetStateAction<Task[]>>;rows:Row[];batches:Batch[];onView:(t:Task)=>void}){
 const [query,setQuery]=React.useState("");const [filter,setFilter]=React.useState("all");const [selected,setSelected]=React.useState<string[]>([]);const [batch,setBatch]=React.useState("");
 const visible=tasks.filter(t=>(t.id+t.fba+t.api+t.trigger).toLowerCase().includes(query.toLowerCase())&&(filter==="all"||filter==="errors"&&["等待重试","需人工"].includes(t.status)||t.status===filter));
 const retryable=(t:Task)=>{const r=rows.find(r=>r.id===t.fba);return !!r&&canRetryDw(r)&&t.status==="等待重试"};
 const retry=(ids:string[])=>{const valid=tasks.filter(t=>ids.includes(t.id)&&retryable(t));setTasks(xs=>xs.map(x=>valid.some(v=>v.id===x.id)?{...x,status:"执行中",next:"限流队列中；执行前重新校验版本"}:x));setSelected([]);toast.success(`已将${valid.length}条有效任务加入重试队列`)};
 return <div className="page"><div className="panel-head"><strong>Amazon任务中心</strong><Button variant="outline" onClick={()=>exportErrors(tasks,rows)}>导出异常</Button></div><section className="panel" style={{marginTop:16}}><div className="panel-head"><strong>人工DW登记批次</strong><select value={batch} onChange={e=>setBatch(e.target.value)}><option value="">选择批次查看登记结果</option>{batches.map(b=><option key={b.id} value={b.id}>{b.id} · {b.target}</option>)}</select></div>{batches.filter(b=>!batch||b.id===batch).slice(0,batch?1:3).map(b=><div key={b.id} style={{padding:16,borderBottom:"1px solid #e2e8f0"}}><strong>{b.id} · {b.source}</strong><p>{b.target} · {b.total}票 · 成功{b.success} / 自动重试{b.retrying} / 失败{b.failed} / 前置等待{b.ineligible}</p><small>{b.created} · {b.operator} · {b.status}；逐票错误和接口执行记录见下表，人工保存记录见货件详情。</small></div>)}</section><section className="panel" style={{marginTop:16}}><div className="panel-head"><strong>执行结果与接口记录</strong><Button disabled={!selected.length} onClick={()=>retry(selected)}>批量重试 {selected.length||""}</Button></div><div style={{display:"flex",gap:12,padding:16}}><Input placeholder="任务号 / FBA货件号 / 接口" value={query} onChange={e=>setQuery(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}>{[["all","全部结果"],["errors","异常结果"],["等待重试","等待重试"],["需人工","需人工"],["执行中","执行中"],["成功","成功"]].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div><div className="table-wrap"><Table><TableHeader><TableRow>{["选择","任务 / FBA货件","接口 / 来源","结果","错误信息","下次动作 / 重试截止","操作"].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.map(t=>{const r=rows.find(r=>r.id===t.fba);return <TableRow key={t.id}><TableCell><input type="checkbox" disabled={!retryable(t)} checked={selected.includes(t.id)} onChange={e=>setSelected(e.target.checked?[...selected,t.id]:selected.filter(x=>x!==t.id))}/></TableCell><TableCell>{t.id}<small className="sub">{t.fba} · {r?.waybill}</small></TableCell><TableCell>{t.api}<small className="sub">{t.trigger}</small></TableCell><TableCell>{t.status}</TableCell><TableCell style={{maxWidth:330,whiteSpace:"normal"}}>{t.error}</TableCell><TableCell>{r?.stopped?"自动处理已结束":r?.settingIssue?"货件设置异常，不可恢复":t.next}</TableCell><TableCell><Button variant="ghost" onClick={()=>onView(t)}>接口记录</Button><Button variant="outline" disabled={!retryable(t)} onClick={()=>retry([t.id])}>重试</Button></TableCell></TableRow>})}</TableBody></Table></div><p style={{padding:16}}>定时调度在后台执行。人工重试沿用前置和停止规则；完成、异常暂停、自动处理结束不能直接重试。客户异常通过导出后线下跟进。</p></section></div>;
}
